# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5284bf84887823a4f1fb411ea42fa2634f14d439e94234105d8b366473f6d2a17d8cd0a89ae83533d0b8771f881cf5a6eb0949908108908bb5b0f15339c5701

test:
  secret_key_base: e402df3e38676339c0d6d8595db243f834b0a4c20af9744ea3422e1304f741f010d27f684b2efc22238cc1cec25d056546c2cd1837bf5b95b42e9894d3d3f9cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
